// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cs04_fluentEfc.Data;

#nullable disable

namespace cs04_fluentEfc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cs04_fluentEfc.Models.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecordId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UserId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            CreatedAt = new DateTime(2024, 9, 26, 9, 29, 34, 650, DateTimeKind.Local).AddTicks(1288),
                            CreatorId = new Guid("201da9f2-de3c-4a0d-9f6a-08df2c61ba15"),
                            Description = "Task 1",
                            UserId = new Guid("dc8032b0-f23c-42e2-a770-99d5ac22b04a")
                        },
                        new
                        {
                            RecordId = 2,
                            CreatedAt = new DateTime(2024, 9, 26, 9, 29, 34, 650, DateTimeKind.Local).AddTicks(1345),
                            CreatorId = new Guid("dc8032b0-f23c-42e2-a770-99d5ac22b04a"),
                            Description = "Task 2",
                            UserId = new Guid("201da9f2-de3c-4a0d-9f6a-08df2c61ba15")
                        });
                });

            modelBuilder.Entity("cs04_fluentEfc.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("201da9f2-de3c-4a0d-9f6a-08df2c61ba15"),
                            Firstname = "John",
                            Lastname = "Doe"
                        },
                        new
                        {
                            UserId = new Guid("dc8032b0-f23c-42e2-a770-99d5ac22b04a"),
                            Firstname = "Jane",
                            Lastname = "Doe"
                        },
                        new
                        {
                            UserId = new Guid("7cf789e7-c508-4f8b-90b4-c200e54c6d6a"),
                            Firstname = "Alice",
                            Lastname = "Smith"
                        },
                        new
                        {
                            UserId = new Guid("19be1d3c-44b3-4055-926a-da1b8b33aa11"),
                            Firstname = "Bob",
                            Lastname = "Smith"
                        });
                });

            modelBuilder.Entity("cs04_fluentEfc.Models.Record", b =>
                {
                    b.HasOne("cs04_fluentEfc.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cs04_fluentEfc.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
